### ISSUE TITLE
What is meaning about '&' in SMILES?

### ISSUE THREAD

**Issue by fanganpai** [Global-Chem/global-chem#1]
Hello,I had noticed that something strange like "C&1&1&1&1" in functional_groups_smiles. RDkit cannot read this.
And I don't think '&' is rightful grammar of [unique SMILES](https://www.daylight.com/dayhtml/doc/theory/theory.smiles.html).
Did you generate it with standard SMILES rules? Or any standard I don't understand is being used? Thanks for your reply.

**Comment by Sulstice** [comment]
Hmm I perhaps should have written where I referenced that from - my mistake. So I don't actually know if the community adopts polymers but Daylight proposed it in his openSMILES specification docs. 

http://opensmiles.org/opensmiles.pdf

Head to that link and then scroll to page 21/25.  It's a way to specify a repeating unit in poylmeys and identifying crystals. I figured I would throw it in there.

Do you think it's worth to keep in? or perhaps separate to a different property in the class `GlobalChem`

**Comment by Sulstice** [comment]
RDKit might not support polymers just yet :(

**Comment by fanganpai** [comment]
Got it.  Just for me, simply remove polymers is effective.
However still few entries there are, and I don't think its necessary to make special treatment for polymers.
By the way, maybe its a good idea to provide an interface to choose "Canonical smiles" & "Isomeric smiles"?

**Comment by Sulstice** [comment]
Yeah, this project there are a couple of things I might want to implement. 

So for folk that is interested in polymer cheminformatics I want to leave that space open for them. There's not many people that do (I also am currently exploring it). 
I'll move it into its own function. 

There was an internal debate in me to whether I would like that have each entry be its own object that has properties like `canonical=True`.

Including I would also like to store info about which SMILES/SMARTS can be processed and by which software so perhaps another property on an entry would be like `allowed_parsers=['RDKit', 'OpenEye', etc...]

So all in all it might look like this

```
        functional_groups_smies = {
            {"1,1,1-trifluoroethane": "CC(F)(F)F", canonical: True, allowed_parsers: ['RDkit']}
```

I think that could work?

**Comment by Sulstice** [comment]
Going to close this one and make a new issue later for handling different software capabilities. The hardest part is getting the nomenclature in initially.
