### ISSUE TITLE
SS-49: [GlobalChem] organization filing and taxes

### ISSUE THREAD

**Issue by Sulstice** [Global-Chem/global-chem#102]
We want to file the Github repository under 501(c)(3) non-profit organization

**Comment by dhavdc** [comment]
From what I have read it should be fairly simple. Not a tax expert so this should be reviewed by other people as well.

### Step 1: 
**Create one of the three:**
For the Internal Revenue Service (the IRS) to recognize an organization's exemption, the organization must be organized as a **trust**, a **corporation**, or an **association**.

In my opinion, an **association** is the easiest to form from what I have read: In general, an association is a group of persons banded together for a specific purpose. To qualify under section 501(a) of the Code, the association must have a written document, such as articles of association, showing its creation. At least two persons must sign the document, which must be dated.

To file a corporation, specific language must be used and trusts don’t apply to our use case.

### Step 2: 
State the organization's tax-exempt purpose. Ours is **educational** (improving skills of individuals or providing useful information to the general public) and **scientific** (research in a manner sufficiently in the public interest and not commercial).

### Step 3: 
File under section 501(c)(3). This requires us to fill out a Form 1023 application. This can be filled out online. https://www.pay.gov/public/form/start/62759871

1. Apply for EIN. https://www.irs.gov/charities-non-profits/the-employer-identification-number

2. New organizations must give financial statements for the **current year** and proposed budgets for **the next two years**, including a detailed breakdown of **revenue** and **expenses**. A section 501(c)(3) organization provides this information on Part VI, Form 1023. 

3. User Fee. User fees for Form 1023 and Form 1023-EZ must be paid online at www.pay.gov when submitting the form

That’s it!
