### ISSUE TITLE
SS-55: [GlobalChemExtensions] Add the OBO graph connection or possible RDF from our JSON structure. 

### ISSUE THREAD

**Issue by Sulstice** [Global-Chem/global-chem#112]
#### Software Selection Candidates:

https://pypi.org/project/Owlready2/
https://github.com/hsolbrig/funowl

#### Documentation:

https://www.w3.org/TR/owl2-syntax/#Structural_Specification

**Comment by Sulstice** [comment]
Let's work on this together

**Comment by cthoyt** [comment]
if you want to do this, it also makes sense to assign stable identifiers. we can also chat about that this week

**Comment by Sulstice** [comment]
Nah github bot keep this one open. We will need it.
