### ISSUE TITLE
CH-1: Map to ChEBI/ChEMBL/other databases

### ISSUE THREAD

**Issue by cthoyt** [Global-Chem/global-chem#117]
would be happy to do some mapping via smiles for you

**Comment by Sulstice** [comment]
@cthoyt Let's do a meeting :) feel like a lot of our goals align.

**Comment by cthoyt** [comment]
cool, you're on EST and I'm on CEST so 9AM for you any day this week works for me

**Comment by Sulstice** [comment]
Yeah sure, lets do tomorrow.
