### ISSUE TITLE
Import from and export to csv/json file

### ISSUE THREAD

**Issue by Ruibin-Liu** [Global-Chem/global-chem#21]
It's common that a user has a list of molecules saved (or can be easily saved) as a csv/json file, so it'll be helpful if the user can add a node(leaf?) directly from a csv/json file.

On the other hand, it can be helpful if a user can export a leaf or several leaves into a csv/json file. A possible use scenario is a user is programming in another language.

**Comment by Sulstice** [comment]
Maybe I'll actually tackle to networkx then users can export to json from there? Since they serve as a pretty big connection piece in the graph world.

**Comment by Sulstice** [comment]
I've added in `global-chem-extensions` to networkx object. And I added a template json file used by threejs for front-end. Check the website and the file in v1.5.1. I think that should be one of the output structures.
