### ISSUE TITLE
SS-136: GlobalChem Virtual Meetup

### ISSUE THREAD

**Issue by Sulstice** [Global-Chem/global-chem#221]
I want to start a possible conference so we can all talk about the direction of the project and status.

**Comment by AnastasiaCroitoru** [comment]
Hi. I am in. However, I am available only after 29th of September

**Comment by LierB** [comment]
Yeah, that's a great idea! October would be best for me.

**Comment by Sulstice** [comment]
Yeah definitely, my comp exam is on Oct. 10 so it would have to be after that.
