### ISSUE TITLE
OT-1: Website (http://www.chemicalgraphtheory.com): not working

### ISSUE THREAD

**Issue by Taoaoxiang** [Global-Chem/global-chem#260]
The website (http://www.chemicalgraphtheory.com) does not work right. 
It has some Chinese name on the title (呼伦贝尔瞬钒环保科技有限公司).

**Comment by Sulstice** [comment]
The website was taken offline and the domain was sold in favour of our new one `www.globalchemistry.org`

Where did you find the link to the old one?
