### ISSUE TITLE
Moving Global-Chem-Extensions into GlobalChem

### ISSUE THREAD

**Issue by Sulstice** [Global-Chem/global-chem#32]
@Ruibin-Liu I did this work on your suggestion but yeah global-chem-extensions now lives within the same repository and attaching the DOI.

**Comment by Sulstice** [comment]
It was done here 21598c946f1a1a0b53b5c718c6a6a9470b2d735b

**Comment by Ruibin-Liu** [comment]
Good job! Since the documentation was already there, it now makes more sense.
