### ISSUE TITLE
SS-31: Potentially bring back Windows for testing

### ISSUE THREAD

**Issue by Sulstice** [Global-Chem/global-chem#69]
Don't know why it's breaking but ubuntu and mac are fine.

**Comment by Sulstice** [comment]
@dhavdc  can I ask you for help?

**Comment by Ruibin-Liu** [comment]
I have updated the file possibly causing the problem. It seemed to pass the windows tests.

**Comment by Sulstice** [comment]
Let me give it shot

**Comment by Sulstice** [comment]
Still Failing for me man.

**Comment by Sulstice** [comment]
Solved.
