### ISSUE TITLE
TK-1: PyYAML library may be old

### ISSUE THREAD

**Issue by Tim-Kirkwood** [Global-Chem/global-chem#72]
I did this code on a Windows 10 laptop:

```
from global_chem import GlobalChem
from global_chem_extensions import GlobalChemExtensions 
gc = GlobalChem() 
gce = GlobalChemExtensions()
global_chem_molecule = gce.initialize_globalchem_molecule('C1CCCC1') 
attributes = global_chem_molecule.get_attributes() 
print (attributes)
```
And got this error:

```
Traceback (most recent call last):

File "my_file", line 30, in <module> global_chem_molecule = gce.initialize_globalchem_molecule('C1CCCC1')

AttributeError: 'GlobalChemExtensions' object has no attribute 'initialize_globalchem_molecule'
```
I installed the library this way (windows 10 cmd line did not like apostrophes):

```
pip install global-chem
pip install global-chem[graphing]
pip install global-chem[forcefields] 
pip install global-chem[bioinformatics] 
pip install global-chem[cheminformaitcs] 
pip install global-chem[quantum_chemistry] 
pip install global-chem[development_operations] 
pip install global-chem[all]
```
When I did `pip install global-chem[quantum_chemistry]` I got this error, which might be the root of my issues? But am unsure how to fix:

```
Installing collected packages: pyyaml
Found existing installation: PyYAML 5.1.1 ERROR: Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```
I'm not sure how to fix this - it looks like my PyYAML has a later version (PyYAML 5.1.1) than yours (pyyaml==3.13) so should not be causing issues?

**Comment by Sulstice** [comment]
Hello,

This is actually a hack on my end to do something. I had a quantum theory final oral examination today and I had to rig psi4 to do a lot of crap in short time. The pyyaml is not the issue but it's actually tied to another issue downstream for a dependency in forte or moly. I forgot. 

The windows issue is actually tied to this, one of our lists actually has some weird encoding on the windows side causing thrings to be weird. @Ruibin-Liu  has a fix for it and I am confirming it now. But it seems his fix is working on windows latest systems:.

https://github.com/Sulstice/global-chem/issues/69

**Comment by Sulstice** [comment]
@Tim-Kirkwood 

Sorry, I re-read your messages. It is not related. I've been doing some refactoring and some of the code has broken. As of today it should be stable but I am writing some tests for the extensions and getting the compliance docs going so it shouldn't be as fragile. Attributes are in the forcefield package (I related them back down to atom types)

Try the new code out:

Load the ForceField Object:

```python

from global_chem_extensions import GlobalChemExtensions
ff = GlobalChemExtensions().forcefields()
```

Load in a SMILES

```python

# Load the Molecule

global_chem_molecule = ff.initialize_globalchem_molecule(
    'FC(F)(C(F)(C(O)=O)F)C(F)(F)F',
)
global_chem_molecule.determine_name()
```

Get the attributes:

```python
attributes = global_chem_molecule.get_attributes()
for k, v in attributes.items():
  print (f'{k}: {v}')
```

Output
```python

name: perfluorobutanoic acid
smiles: FC(F)(C(F)(C(O)=O)F)C(F)(F)F
molecular_weight: 213.986476812
logp: 1.9039000000000001
h_bond_donor: 1
h_bond_acceptors: 1
rotatable_bonds: 2
number_of_atoms: 13
molar_refractivity: 23.5848
topological_surface_area_mapping: 37.3
formal_charge: 0
heavy_atoms: 13
num_of_rings: 0
```

**Comment by Sulstice** [comment]
The pyyaml library was used to get around a bug in `moly` calling for a different Loader object. The hot fix was to change the version and where the long-term fix is to change the moly core code and release a new package with updated pyyaml parameters. 

Do you need the quantum chemistry package?

```
pip install global-chem[cheminformaitcs] 
```

You can just download the cheminformatic one if that's all you need it for. If you need the quantum chemistry package you will have to wait for the long term fix.

**Comment by Sulstice** [comment]
I this is solved and should be handled.
