### ISSUE TITLE
DK-1: Improve smiles drawing performance on flashcards

### ISSUE THREAD

**Issue by dhavdc** [Global-Chem/global-chem#90]
Move the initialization of the smilesDrawer outside of the drawSmiles function. Might provide a performance boost since we don't need to initialize it every slide. 

https://github.com/Sulstice/global-chem/blob/6f7037f6973ada7f42bdf1bc5412a40f82c363c3/front_end/flashcards/src/scripts/flashcards.js#L113

**Comment by Sulstice** [comment]
Can you provide more instructions for someone that is new. Maybe show the lines of the function, where, and tell them why you think it would perform a performance boost.

**Comment by Sulstice** [comment]
To be honest, it's really good and this is not needed. Extra work for no benefit.
