### ISSUE TITLE
RL-2: Inconsistency in SMILES

### ISSUE THREAD

**Issue by Ruibin-Liu** [Global-Chem/global-chem#94]
Sometimes a same compound appears twice but has two different SMILES. For example,  'mescaline' is in
https://github.com/Sulstice/global-chem/blob/c22d6b196f31d249eda4087f812da0b0d610a897/global_chem/global_chem/narcotics/pihkal.py#L112 and 
https://github.com/Sulstice/global-chem/blob/c22d6b196f31d249eda4087f812da0b0d610a897/global_chem/global_chem/narcotics/schedule_one.py#L154
The first 'style' is used several times in the `pihkal.py` file like:
https://github.com/Sulstice/global-chem/blob/c22d6b196f31d249eda4087f812da0b0d610a897/global_chem/global_chem/narcotics/pihkal.py#L36

Please fix them.

**Comment by Sulstice** [comment]
This is because Shulgin, author of PihKal, released the book with MDL files back at UC Berkeley. He knew eventually someone wanted to mine his data. 

Getting the names and the files and converted to SMILES to some work but yeah I didn't do a sanity check. I will fix it now.

**Comment by Sulstice** [comment]
c22d6b196f31d249eda4087f812da0b0d610a897 Fixed Here
